# plugins/auth-boundary.toml
["modules/@mindbaz/zonemta-auth-boundary"]
enabled="receiver"

# to which SMTP interfaces this plugin applies to. Use "*" for all interfaces
interfaces=["feeder"]

# Boundary URL
boundary_url="http://127.0.0.1:8080"
